name: maven pipeline
on:
  workflow_call:
     outputs:
        dockerImage: 
           value: ${{ jobs.docker.outputs.output1 }}
jobs:
    docker:
      runs-on: ubuntu-latest
      outputs:
         output1: ${{ steps.step1.outputs.dockerImage }}
      steps:
        - id: step1
          run: echo "::set-output name=dockerImage::'Dockerfile'"
        - name: building image 
          run: echo "image"
        - name: building image 
          run: |
               pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile.txt" -OutFile "Dockerfile.txt"'
        - name: building docker image
          run: |
              ls -l
              readlink -f Dockerfile.txt
      
