name: Angular pipeline
on:
  workflow_call:
     outputs:
        dockerImage: 
           value: ${{ jobs.docker.outputs.output1 }}
jobs:
    build:
      runs-on: ubuntu-latest
      outputs:
         output1: ${{ steps.step1.outputs.dockerImage }}
      steps:
        - id: step1
          run: echo "::set-output name=dockerImage::'Dockerfile'"
        - name: building image 
          run: |
               pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile" -OutFile "Dockerfile"'
          - name: building docker image
            run: |
                ls -l
                readlink -f Dockerfile
    publish-Artifact:
      runs-on: ubuntu-latest
      needs: Quality-Gates
      steps:
        - uses: actions/checkout@v3
        - name: github uploading
          uses: actions/upload-artifact@v3
          with:
            name: 'Dockerfile'
            path: /home/runner/work/Project/Project/Dockerfile
        - name: uploading to jFrog
          run: echo 'jfrog'
