name: npm pipeline
on: 
  workflow_call:
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
          - name: installing docker image
            run: |
                pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile" -OutFile "Dockerfile"'
          - name: building docker image
            run: |
                ls -l
                readlink -f Dockerfile

