name: npm pipeline
on: 
  workflow_call:
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
         - uses: docker/setup-buildx-action@v2
           id: buildx
           with:
             install: true
         - name: Build
           run: |
             docker build .
