name: inputs
on:
  workflow_call:
        inputs:
            pipelinetype:
                required: true
                type: string
            buildTool:
                required: true
                type: string
            language:
                required: true
                type: string
jobs:
    inputs:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: just checking
           run: echo "running"
